In [12]:
import numpy as np

In [13]:
arr1=[1,2,3,4,5,6,7,8,9]
arr=np.array(arr1)
type(arr)
arr.shape
arr.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
square=arr**2
square

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [42]:
#functions
arra1=np.array([1,2,3,4,5,6,7,8])
arra2=np.array([[1,2,3,4],[5,6,7,8]])
np.zeros((2,3))
np.ones((3,9))
np.full((1,4),90)
np.arange(1,10,1)
np.linspace(0,1000,20)

array([   0.        ,   52.63157895,  105.26315789,  157.89473684,
        210.52631579,  263.15789474,  315.78947368,  368.42105263,
        421.05263158,  473.68421053,  526.31578947,  578.94736842,
        631.57894737,  684.21052632,  736.84210526,  789.47368421,
        842.10526316,  894.73684211,  947.36842105, 1000.        ])

In [41]:
arr5=np.arange(10,101)#execise
arr5
arr5.shape

(91,)

In [59]:
array=np.array([21,33,46,34,56,92,87,68])
array.shape
type(array)
array.size
array.ndim
array.dtype
arrr=np.array([2,4,6,8,0],dtype=np.int32)
arrr.dtype
arrr1=arrr.astype(np.float64)
arrr1.dtype

dtype('float64')

In [91]:
arr=np.arange(1,20,5)
arr
arr.size
arr.reshape((2,2))
arr.flatten()
arr
arr[:2]
arr[[0]]

np.int64(1)

In [79]:
arr = np.array([10, 20, 30, 40, 50])
sliced = arr[1:4]
sliced[0] = 999
print(arr) 

[ 10 999  30  40  50]


In [84]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4] # Indices to select
print(arr[idx]) # [10 30 50|

[10 30 50]


In [90]:
arr=np.arange(0,200,5)
arr
mask=arr>50
arr[mask]

array([ 55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115,
       120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180,
       185, 190, 195])

In [94]:
arr=np.array([[2,4],[5,6],[3,4]])
arr
arr[: ,0:1]

array([[2],
       [5],
       [3]])

In [99]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])
arr3D.shape
arr3D[0:1,1:,1:]
arr3D[1,0,1:]


array([8, 9])

In [101]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
mean

array([20., 30., 40.])